# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  cleanup_finished_jobs:
    class: "MaintenanceJob"
    schedule: every hour at minute 12

  cleanup_old_events:
    class: "CleanupEventsJob"
    schedule: at 2am every day

production:
  cleanup_finished_jobs:
    class: "MaintenanceJob"
    schedule: every hour at minute 12

  cleanup_old_events:
    class: "CleanupEventsJob"
    schedule: at 2am every day
